# Custom Language File for Launcher Customizer

[ejs.app]
title = "Eunso Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/GuEunso/EunsoLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/QT6fy8d4Nw"

[ejs.settings]
sourceGithubLink = "https://github.com/GuEunso/EunsoLauncher"
supportLink = "https://github.com/GuEunso/EunsoLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO EUNSOLAUNCHER"
welcomeDescription = ""
welcomeDescCTA = ""
